[package]
name = "untd"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
chrono-tz = "0.10"
clap = { version = "4.5", features = ["derive"] }
arboard = "3.3"

[profile.release]
lto = true
codegen-units = 1
